name: Build and Test - Population Reporting System
on:
  push:
      branches:
        - master

permissions:
  contents: write

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Unit Tests
        run: |
          mvn -Dtest=com.napier.sem.GenerateCityReportsTest test
          mvn -Dtest=com.napier.sem.TopNCityReportsTest test
          mvn -Dtest=com.napier.sem.GeneralPopulationReportsTest test
          mvn -Dtest=com.napier.sem.PopulationReportTest test
          mvn -Dtest=com.napier.sem.CountryReportTest test
          mvn -Dtest=com.napier.sem.CapitalCityReportTest test
      - name: List dirs
        run: |
          cd ./target/site/jacoco
          pwd
          ls
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  #       directory: ./target/site/jacoco
  #          verbose: true # optional (default = false)



  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Integration Tests and CodeCov
        run: |
          docker build -t database ./database 
          docker run --name employees -dp 33060:3306 database
          mvn -Dtest=com.napier.sem.GenerateCityReportsIntegrationTest test
          mvn -Dtest=com.napier.sem.TopNCityReportsIntegrationTest test
          mvn -Dtest=com.napier.sem.PopulationReportsIntegrationTest test
          mvn -Dtest=com.napier.sem.GeneralPopulationReportsIntegrationTest test
          mvn -Dtest=com.napier.sem.CountryReportIntegrationTest test
           mvn -Dtest=com.napier.sem.CapitalCityReportIntegrationTest test
          docker stop employees
          docker rm employees
          docker image rm database
      - name: Shutdown
        run: docker compose down
      - name: CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)
  build:
    name: Build and Start Using docker-compose
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker compose up --abort-on-container-exit
      - name: Copy Output
        run: docker container cp group-20--app-1:./tmp/reports ./
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: reports # The branch the action should deploy to.
          folder: reports # The folder we are copying

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            ./target/*.jar